groups:
- name: kubernetes
  rules:
  - alert: kube-cpu-quota-overcommit-warning
    expr: >-
      sum by (cluster) ( min without(resource) (kube_resourcequota{job="kube-state-metrics", type="hard", resource=~"(cpu|requests.cpu)"}) ) / sum by (cluster) ( kube_node_status_allocatable{resource="cpu", job="kube-state-metrics"} ) > 1.5
    for: 5m
    labels:
      severity: warning
      group_name: kube-cpu-quota-overcommit
      node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
    annotations:
      description: Cluster {{ $labels.cluster }} has overcommitted CPU resource requests for Namespaces.
      runbook_url: default_runbook_url
      summary: Cluster has overcommitted CPU resource requests.
      dashboard_url: default_dashboard_url
  - alert: kube-cpu-quota-overcommit-critical
    expr: >-
      sum by (cluster) ( min without(resource) (kube_resourcequota{job="kube-state-metrics", type="hard", resource=~"(cpu|requests.cpu)"}) ) / sum by (cluster) ( kube_node_status_allocatable{resource="cpu", job="kube-state-metrics"} ) > 1.5
    for: 5m
    labels:
      severity: critical
      group_name: kube-cpu-quota-overcommit
      node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
    annotations:
      description: Cluster {{ $labels.cluster }} has overcommitted CPU resource requests for Namespaces.
      runbook_url: default_runbook_url
      summary: Cluster has overcommitted CPU resource requests.
      dashboard_url: default_dashboard_url
