groups:
  - name: kubernetes
    rules:
      - alert: kube-job-not-completed-warning
        expr: >-
          time() - max by (namespace, job_name, cluster) (kube_job_status_start_time{job="kube-state-metrics", namespace=~".*"}

          and kube_job_status_active{job="kube-state-metrics", namespace=~".*"} > 0) > 43200
        for: 0m
        labels:
          severity: warning
          group_name: kube-job-not-completed
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: Job {{ $labels.namespace }}/{{ $labels.job_name }} is taking more than {{ "43200" | humanizeDuration }} to complete on cluster {{ $labels.cluster }}.
          runbook_url: default_runbook_url
          summary: Job did not complete in time
          dashboard_url: default_dashboard_url
      - alert: kube-job-not-completed-critical
        expr: >-
          time() - max by (namespace, job_name, cluster) (kube_job_status_start_time{job="kube-state-metrics", namespace=~".*"}

          and kube_job_status_active{job="kube-state-metrics", namespace=~".*"} > 0) > 43200
        for: 0m
        labels:
          severity: critical
          group_name: kube-job-not-completed
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: Job {{ $labels.namespace }}/{{ $labels.job_name }} is taking more than {{ "43200" | humanizeDuration }} to complete on cluster {{ $labels.cluster }}.
          runbook_url: default_runbook_url
          summary: Job did not complete in time
          dashboard_url: default_dashboard_url
