groups:
- name: kubernetes
  rules:
  - alert: kube-deployment-rollout-stuck-warning
    expr: kube_deployment_status_condition{condition="Progressing", status="false",job="kube-state-metrics", namespace=~".*"} != 0
    for: 15m
    labels:
      severity: warning
      group_name: kube-deployment-rollout-stuck
      node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
    annotations:
      description: Rollout of deployment {{ $labels.namespace }}/{{ $labels.deployment }} is not progressing for longer than 15 minutes on cluster {{ $labels.cluster }}.
      runbook_url: default_runbook_url
      summary: Deployment rollout is not progressing.
      dashboard_url: default_dashboard_url
  - alert: kube-deployment-rollout-stuck-critical
    expr: kube_deployment_status_condition{condition="Progressing", status="false",job="kube-state-metrics", namespace=~".*"} != 0
    for: 15m
    labels:
      severity: critical
      group_name: kube-deployment-rollout-stuck
      node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
    annotations:
      description: Rollout of deployment {{ $labels.namespace }}/{{ $labels.deployment }} is not progressing for longer than 15 minutes on cluster {{ $labels.cluster }}.
      runbook_url: default_runbook_url
      summary: Deployment rollout is not progressing.
      dashboard_url: default_dashboard_url
