groups:
- name: kubernetes
  rules:
  - alert: kube-state-metrics-shards-missing-warning
    expr: >-
      2^max(kube_state_metrics_total_shards{job="kube-state-metrics"}) by (cluster) - 1 - sum( 2 ^ max by (cluster, shard_ordinal) (kube_state_metrics_shard_ordinal{job="kube-state-metrics"}) ) by (cluster) != 0
    for: 15m
    labels:
      severity: warning
      group_name: kube-state-metrics-shards-missing
      node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
    annotations:
      description: kube-state-metrics shards are missing, some Kubernetes objects are not being exposed.
      runbook_url: default_runbook_url
      summary: kube-state-metrics shards are missing.
      dashboard_url: default_dashboard_url
  - alert: kube-state-metrics-shards-missing-critical
    expr: >-
      2^max(kube_state_metrics_total_shards{job="kube-state-metrics"}) by (cluster) - 1 - sum( 2 ^ max by (cluster, shard_ordinal) (kube_state_metrics_shard_ordinal{job="kube-state-metrics"}) ) by (cluster) != 0
    for: 15m
    labels:
      severity: critical
      group_name: kube-state-metrics-shards-missing
      node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
    annotations:
      description: kube-state-metrics shards are missing, some Kubernetes objects are not being exposed.
      runbook_url: default_runbook_url
      summary: kube-state-metrics shards are missing.
      dashboard_url: default_dashboard_url
