groups:
- name: kubernetes
  rules:
  - alert: kube-hpa-maxed-out-warning
    expr: >-
      kube_horizontalpodautoscaler_status_current_replicas{job="kube-state-metrics", namespace=~".*"} == kube_horizontalpodautoscaler_spec_max_replicas{job="kube-state-metrics", namespace=~".*"}
    for: 15m
    labels:
      severity: warning
      group_name: kube-hpa-maxed-out
      node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
    annotations:
      description: HPA {{ $labels.namespace }}/{{ $labels.horizontalpodautoscaler  }} has been running at max replicas for longer than 15 minutes on cluster {{ $labels.cluster }}.
      runbook_url: default_runbook_url
      summary: HPA is running at max replicas
      dashboard_url: default_dashboard_url
  - alert: kube-hpa-maxed-out-critical
    expr: >-
      kube_horizontalpodautoscaler_status_current_replicas{job="kube-state-metrics", namespace=~".*"} == kube_horizontalpodautoscaler_spec_max_replicas{job="kube-state-metrics", namespace=~".*"}
    for: 15m
    labels:
      severity: critical
      group_name: kube-hpa-maxed-out
      node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
    annotations:
      description: HPA {{ $labels.namespace }}/{{ $labels.horizontalpodautoscaler  }} has been running at max replicas for longer than 15 minutes on cluster {{ $labels.cluster }}.
      runbook_url: default_runbook_url
      summary: HPA is running at max replicas
      dashboard_url: default_dashboard_url
