groups:
  - name: kubernetes
    rules:
      - alert: kube-quota-fully-used-warning
        expr: >-
          kube_resourcequota{job="kube-state-metrics", type="used"} / ignoring(instance, job, type) (kube_resourcequota{job="kube-state-metrics", type="hard"} > 0) == 1
        for: 15m
        labels:
          severity: warning
          group_name: kube-quota-fully-used
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its {{ $labels.resource }} quota on cluster {{ $labels.cluster }}.
          runbook_url: default_runbook_url
          summary: Namespace quota is fully used.
          dashboard_url: default_dashboard_url
      - alert: kube-quota-fully-used-critical
        expr: >-
          kube_resourcequota{job="kube-state-metrics", type="used"} / ignoring(instance, job, type) (kube_resourcequota{job="kube-state-metrics", type="hard"} > 0) == 1
        for: 15m
        labels:
          severity: critical
          group_name: kube-quota-fully-used
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: Namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its {{ $labels.resource }} quota on cluster {{ $labels.cluster }}.
          runbook_url: default_runbook_url
          summary: Namespace quota is fully used.
          dashboard_url: default_dashboard_url
