groups:
- name: kubernetes
  rules:
  - alert: kube-daemonset-rollout-stuck-warning
    expr: >-
      ( ( kube_daemonset_status_current_number_scheduled{job="kube-state-metrics", namespace=~".*"} != kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"} )

      or ( kube_daemonset_status_number_misscheduled{job="kube-state-metrics", namespace=~".*"} != 0 )

      or ( kube_daemonset_status_updated_number_scheduled{job="kube-state-metrics", namespace=~".*"} != kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"} )

      or ( kube_daemonset_status_number_available{job="kube-state-metrics", namespace=~".*"} != kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"} ) )

      and ( changes(kube_daemonset_status_updated_number_scheduled{job="kube-state-metrics", namespace=~".*"}[5m]) == 0 )
    for: 15m
    labels:
      severity: warning
      group_name: kube-daemonset-rollout-stuck
      node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
    annotations:
      description: DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} has not finished or progressed for at least 15m on cluster {{ $labels.cluster }}.
      runbook_url: default_runbook_url
      summary: DaemonSet rollout is stuck.
      dashboard_url: default_dashboard_url
  - alert: kube-daemonset-rollout-stuck-critical
    expr: >-
      ( ( kube_daemonset_status_current_number_scheduled{job="kube-state-metrics", namespace=~".*"} != kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"} )

      or ( kube_daemonset_status_number_misscheduled{job="kube-state-metrics", namespace=~".*"} != 0 )

      or ( kube_daemonset_status_updated_number_scheduled{job="kube-state-metrics", namespace=~".*"} != kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"} )

      or ( kube_daemonset_status_number_available{job="kube-state-metrics", namespace=~".*"} != kube_daemonset_status_desired_number_scheduled{job="kube-state-metrics", namespace=~".*"} ) )

      and ( changes(kube_daemonset_status_updated_number_scheduled{job="kube-state-metrics", namespace=~".*"}[5m]) == 0 )
    for: 15m
    labels:
      severity: critical
      group_name: kube-daemonset-rollout-stuck
      node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
    annotations:
      description: DaemonSet {{ $labels.namespace }}/{{ $labels.daemonset }} has not finished or progressed for at least 15m on cluster {{ $labels.cluster }}.
      runbook_url: default_runbook_url
      summary: DaemonSet rollout is stuck.
      dashboard_url: default_dashboard_url
