groups:
  - name: kubernetes
    rules:
      - alert: kube-state-metrics-watch-errors-warning
        expr: >-
          (sum(rate(kube_state_metrics_watch_total{job="kube-state-metrics",result="error"}[5m])) by (cluster) / sum(rate(kube_state_metrics_watch_total{job="kube-state-metrics"}[5m])) by (cluster)) > 0.01
        for: 15m
        labels:
          severity: warning
          group_name: kube-state-metrics-watch-errors
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: kube-state-metrics is experiencing errors at an elevated rate in watch operations. This is likely causing it to not be able to expose metrics about Kubernetes objects correctly or at all.
          runbook_url: default_runbook_url
          summary: kube-state-metrics is experiencing errors in watch operations.
          dashboard_url: default_dashboard_url
      - alert: kube-state-metrics-watch-errors-critical
        expr: >-
          (sum(rate(kube_state_metrics_watch_total{job="kube-state-metrics",result="error"}[5m])) by (cluster) / sum(rate(kube_state_metrics_watch_total{job="kube-state-metrics"}[5m])) by (cluster)) > 0.01
        for: 15m
        labels:
          severity: critical
          group_name: kube-state-metrics-watch-errors
          node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
        annotations:
          description: kube-state-metrics is experiencing errors at an elevated rate in watch operations. This is likely causing it to not be able to expose metrics about Kubernetes objects correctly or at all.
          runbook_url: default_runbook_url
          summary: kube-state-metrics is experiencing errors in watch operations.
          dashboard_url: default_dashboard_url
