groups:
- name: kubernetes
  rules:
  - alert: kube-container-waiting-warning
    expr: kube_pod_container_status_waiting_reason{reason!="CrashLoopBackOff", job="kube-state-metrics", namespace=~".*"} > 0
    for: 1h
    labels:
      severity: warning
      group_name: kube-container-waiting
      node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
    annotations:
      description: 'pod/{{ $labels.pod }} in namespace {{ $labels.namespace }} on container {{ $labels.container}} has been in waiting state for longer than 1 hour. (reason: "{{ $labels.reason }}") on cluster {{ $labels.cluster }}.'
      runbook_url: default_runbook_url
      summary: Pod container waiting longer than 1 hour
      dashboard_url: default_dashboard_url
  - alert: kube-container-waiting-critical
    expr: kube_pod_container_status_waiting_reason{reason!="CrashLoopBackOff", job="kube-state-metrics", namespace=~".*"} > 0
    for: 1h
    labels:
      severity: critical
      group_name: kube-container-waiting
      node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
    annotations:
      description: 'pod/{{ $labels.pod }} in namespace {{ $labels.namespace }} on container {{ $labels.container}} has been in waiting state for longer than 1 hour. (reason: "{{ $labels.reason }}") on cluster {{ $labels.cluster }}.'
      runbook_url: default_runbook_url
      summary: Pod container waiting longer than 1 hour
      dashboard_url: default_dashboard_url
