additionalPrometheusRulesMap:
  kube-job-not-completed:
    groups:
      - name: kube-job-not-completed
        rules:
          - alert: kube-job-not-completed-warning
            expr: >-
              time() - max by (namespace, job_name) (kube_job_status_start_time{namespace=~".*"}

              and kube_job_status_active{namespace=~".*"} > 0) > 43200
            for: 5m
            labels:
              severity: warning
              group_name: kube-job-not-completed
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                Job {{ $labels.namespace }}/{{ $labels.job_name }} is taking more than {{ "43200" |
                humanizeDuration }} to complete. This warning alert fires after
                5m.
              runbook_url: default_runbook_url
              summary: Job did not complete in time
              dashboard_url: default_dashboard_url
          - alert: kube-job-not-completed-critical
            expr: >-
              time() - max by (namespace, job_name) (kube_job_status_start_time{namespace=~".*"}

              and kube_job_status_active{namespace=~".*"} > 0) > 43200
            for: 10m
            labels:
              severity: critical
              group_name: kube-job-not-completed
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                Job {{ $labels.namespace }}/{{ $labels.job_name }} is taking more than {{ "43200" |
                humanizeDuration }} to complete. This critical alert fires after 10m.
              runbook_url: default_runbook_url
              summary: Job did not complete in time
              dashboard_url: default_dashboard_url
