additionalPrometheusRulesMap:
  kube-persistent-volume-filling-up:
    groups:
      - name: kube-persistent-volume-filling-up
        rules:
          - alert: kube-persistent-volume-filling-up-warning
            expr: >-
              ( kubelet_volume_stats_available_bytes{namespace=~".*", metrics_path="/metrics"} / kubelet_volume_stats_capacity_bytes{namespace=~".*", metrics_path="/metrics"} ) < 0.15

              and kubelet_volume_stats_used_bytes{namespace=~".*", metrics_path="/metrics"} > 0

              and predict_linear(kubelet_volume_stats_available_bytes{namespace=~".*", metrics_path="/metrics"}[6h], 10 * 24 * 3600) < 0

              unless on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_access_mode{access_mode="ReadOnlyMany"} == 1
            for: 5m
            labels:
              severity: warning
              group_name: kube-persistent-volume-filling-up
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                Based on recent sampling, the PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in
                Namespace {{ $labels.namespace }} is expected to fill up within ten days.
                Currently {{ $value | humanizePercentage }} is available.
                This warning alert fires after 5m.
              runbook_url: default_runbook_url
              summary: PersistentVolume is filling up.
              dashboard_url: default_dashboard_url
          - alert: kube-persistent-volume-filling-up-critical
            expr: >-
              ( kubelet_volume_stats_available_bytes{namespace=~".*", metrics_path="/metrics"} / kubelet_volume_stats_capacity_bytes{namespace=~".*", metrics_path="/metrics"} ) < 0.15

              and kubelet_volume_stats_used_bytes{namespace=~".*", metrics_path="/metrics"} > 0

              and predict_linear(kubelet_volume_stats_available_bytes{namespace=~".*", metrics_path="/metrics"}[6h], 4 * 24 * 3600) < 0

              unless on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_access_mode{access_mode="ReadOnlyMany"} == 1
            for: 10m
            labels:
              severity: critical
              group_name: kube-persistent-volume-filling-up
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                Based on recent sampling, the PersistentVolume claimed by {{ $labels.persistentvolumeclaim }} in
                Namespace {{ $labels.namespace }} is expected to fill up within four days.
                Currently {{ $value | humanizePercentage }} is available.
                This critical alert fires after 10m.
              runbook_url: default_runbook_url
              summary: PersistentVolume is filling up.
              dashboard_url: default_dashboard_url
