additionalPrometheusRulesMap:
  kube-pod-not-ready:
    groups:
      - name: kube-pod-not-ready
        rules:
          - alert: kube-pod-not-ready-warning
            expr: >-
              sum by (namespace, pod) ( max by (namespace, pod) ( kube_pod_status_phase{namespace=~".*", phase=~"Pending|Failed|Unknown"} == 1 ) * on (namespace, pod) group_left(owner_kind) topk by (namespace, pod) ( 1, max by (namespace, pod, owner_kind) (kube_pod_owner{owner_kind!="Job"}) ) ) > 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-pod-not-ready
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 5
                minutes.
              runbook_url: default_runbook_url
              summary: Pod has been in a non-ready state for more than 5 minutes.
              dashboard_url: default_dashboard_url
          - alert: kube-pod-not-ready-critical
            expr: >-
              sum by (namespace, pod) ( max by (namespace, pod) ( kube_pod_status_phase{namespace=~".*", phase=~"Pending|Failed|Unknown"} == 1 ) * on (namespace, pod) group_left(owner_kind) topk by (namespace, pod) ( 1, max by (namespace, pod, owner_kind) (kube_pod_owner{owner_kind!="Job"}) ) ) > 0
            for: 10m
            labels:
              severity: critical
              group_name: kube-pod-not-ready
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 10
                minutes.
              runbook_url: default_runbook_url
              summary: Pod has been in a non-ready state for more than 10 minutes.
              dashboard_url: default_dashboard_url
