additionalPrometheusRulesMap:
  kube-hpa-replicas-mismatch:
    groups:
      - name: kube-hpa-replicas-mismatch
        rules:
          - alert: kube-hpa-replicas-mismatch-warning
            expr: >-
              (kube_horizontalpodautoscaler_status_desired_replicas{namespace=~".*"} != kube_horizontalpodautoscaler_status_current_replicas{namespace=~".*"})

              and (kube_horizontalpodautoscaler_status_current_replicas{ namespace=~".*"} > kube_horizontalpodautoscaler_spec_min_replicas{namespace=~".*"})

              and (kube_horizontalpodautoscaler_status_current_replicas{namespace=~".*"} < kube_horizontalpodautoscaler_spec_max_replicas{namespace=~".*"})

              and changes(kube_horizontalpodautoscaler_status_current_replicas{namespace=~".*"}[15m]) == 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-hpa-replicas-mismatch
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                HPA {{ $labels.namespace }}/{{ $labels.horizontalpodautoscaler  }} has not matched the desired
                number of replicas for longer than 5 minutes on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: HPA has not matched desired number of replicas.
              dashboard_url: default_dashboard_url
          - alert: kube-hpa-replicas-mismatch-critical
            expr: >-
              (kube_horizontalpodautoscaler_status_desired_replicas{namespace=~".*"} != kube_horizontalpodautoscaler_status_current_replicas{namespace=~".*"})

              and (kube_horizontalpodautoscaler_status_current_replicas{ namespace=~".*"} > kube_horizontalpodautoscaler_spec_min_replicas{namespace=~".*"})

              and (kube_horizontalpodautoscaler_status_current_replicas{namespace=~".*"} < kube_horizontalpodautoscaler_spec_max_replicas{namespace=~".*"})

              and changes(kube_horizontalpodautoscaler_status_current_replicas{namespace=~".*"}[15m]) == 0
            for: 10m
            labels:
              severity: critical
              group_name: kube-hpa-replicas-mismatch
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                HPA {{ $labels.namespace }}/{{ $labels.horizontalpodautoscaler  }} has not matched the desired
                number of replicas for longer than 10 minutes on cluster {{ $labels.cluster }}.
              runbook_url: default_runbook_url
              summary: HPA has not matched desired number of replicas.
              dashboard_url: default_dashboard_url
