additionalPrometheusRulesMap:
  kube-memory-overcommit:
    groups:
      - name: kube-memory-overcommit
        rules:
          - alert: kube-memory-overcommit-warning
            expr: >-
              (( sum(namespace_memory:kube_pod_container_resource_requests:sum{}) - sum(kube_node_status_allocatable{job="kube-state-metrics", resource="memory"})) > 0

              and count( max by (node) (kube_node_role{job="kube-state-metrics", role="control-plane"})) < 3)

              or (sum(namespace_memory:kube_pod_container_resource_requests:sum{}) - (sum(kube_node_status_allocatable{job="kube-state-metrics", resource="memory"}) - max(kube_node_status_allocatable{job="kube-state-metrics", resource="memory"}))) > 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-memory-overcommit
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                Cluster has overcommitted memory resource requests for Pods by {{ $value |
                humanize }} bytes and cannot tolerate node failure. This warning alert fires after 5m.
              runbook_url: default_runbook_url
              summary: Cluster has overcommitted memory resource requests.
              dashboard_url: default_dashboard_url
          - alert: kube-memory-overcommit-critical
            expr: >-
              (( sum(namespace_memory:kube_pod_container_resource_requests:sum{}) - sum(kube_node_status_allocatable{job="kube-state-metrics", resource="memory"})) > 0

              and count( max by (node) (kube_node_role{job="kube-state-metrics", role="control-plane"})) < 3)

              or (sum(namespace_memory:kube_pod_container_resource_requests:sum{}) - (sum(kube_node_status_allocatable{job="kube-state-metrics", resource="memory"}) - max(kube_node_status_allocatable{job="kube-state-metrics", resource="memory"}))) > 0
            for: 10m
            labels:
              severity: critical
              group_name: kube-memory-overcommit
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                Cluster has overcommitted memory resource requests for Pods by {{ $value |
                humanize }} bytes and cannot tolerate node failure. This critical alert fires after 10m.
              runbook_url: default_runbook_url
              summary: Cluster has overcommitted memory resource requests.
              dashboard_url: default_dashboard_url
