additionalPrometheusRulesMap:
  kube-deployment-generation-mismatch:
    groups:
      - name: kube-deployment-generation-mismatch
        rules:
          - alert: kube-deployment-generation-mismatch-warning
            expr: >-
              kube_deployment_status_observed_generation{namespace=~".*"} != kube_deployment_metadata_generation{ namespace=~".*"}
            for: 5m
            labels:
              severity: warning
              group_name: kube-deployment-generation-mismatch
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment }} does not match, this
                indicates that the Deployment has failed but has not been rolled back on cluster {{
                $labels.cluster }}. This warning alert fires after 5m.
              runbook_url: default_runbook_url
              summary: Deployment generation mismatch due to possible roll-back
              dashboard_url: default_dashboard_url
          - alert: kube-deployment-generation-mismatch-critical
            expr: >-
              kube_deployment_status_observed_generation{namespace=~".*"} != kube_deployment_metadata_generation{namespace=~".*"}
            for: 10m
            labels:
              severity: critical
              group_name: kube-deployment-generation-mismatch
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                Deployment generation for {{ $labels.namespace }}/{{ $labels.deployment }} does not match, this
                indicates that the Deployment has failed but has not been rolled back on cluster {{
                $labels.cluster }}. This critical alert fires after 10m.
              runbook_url: default_runbook_url
              summary: Deployment generation mismatch due to possible roll-back
              dashboard_url: default_dashboard_url
