additionalPrometheusRulesMap:
  kube-persistent-volume-errors:
    groups:
      - name: kube-persistent-volume-errors
        rules:
          - alert: kube-persistent-volume-errors-warning
            expr: kube_persistentvolume_status_phase{phase=~"Failed|Pending"} > 0
            for: 5m
            labels:
              severity: warning
              group_name: kube-persistent-volume-errors
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                The persistent volume {{ $labels.persistentvolume }} has status {{ $labels.phase }}.
                This warning alert fires after 5m.
              runbook_url: default_runbook_url
              summary: PersistentVolume is having issues with provisioning.
              dashboard_url: default_dashboard_url
          - alert: kube-persistent-volume-errors-critical
            expr: kube_persistentvolume_status_phase{phase=~"Failed|Pending"} > 0
            for: 10m
            labels:
              severity: critical
              group_name: kube-persistent-volume-errors
              node_hostname: '{{ reReplaceAll ":.*" "" $labels.instance }}'
            annotations:
              description: >-
                The persistent volume {{ $labels.persistentvolume }} has status {{ $labels.phase }}.
                This critical alert fires after 10m.
              runbook_url: default_runbook_url
              summary: PersistentVolume is having issues with provisioning.
              dashboard_url: default_dashboard_url
